# Smart Customer Data Analysis System 

## Projenin Amacı:
Pandas kütüphanesinin temel yapı taşlarını kullanarak gerçek hayatta karşılığı olan müşteri harcama verilerini analiz etmektir.

## Pandas Neden Kullanılır?
- Tablo bazlı verilerle çalışmayı kolaylaştırır.
- Veriye anlamlı indeksler atamayı sağlar.
- Gerçek hayattaki müşteri, satış ve finans verilerini analiz etmek için idealdir.

# Bu Projede Kullanılan Pandas Konuları:
- Pandas giriş
- Series
- Series özellikleri
- DataFrame
- DataFrame indeksler
- İndeks değiştirme
- Multi-index

In [4]:
import pandas as pd

#2 Aylık harcamaları temsil eden bir series oluştur ve indeks olarak ay isimlerini kullan
harcananPara = [2000, 4050, 3300, 5060, 9195, 8200]
aylar = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran"] #6 ay öğrenmesi için yeterlidir
monthlySpending = pd.Series(data=harcananPara, index=aylar, name="Aylık harcamalar")
monthlySpending

Ocak       2000
Şubat      4050
Mart       3300
Nisan      5060
Mayıs      9195
Haziran    8200
Name: Aylık harcamalar, dtype: int64

In [8]:
#3 Series Özellikleri
# values, index, dtype, ortalama harcama

#Seri içindeki değerler
seriesValues = monthlySpending.values
print(f"Seri içindeki değerler: {seriesValues}")

#index bilgisi
indexSeries = monthlySpending.index
print(f"Seri içindeki indeksler: {indexSeries}")

#veri tipi
dataTypeSeries = monthlySpending.dtype
print(f"Seri içindeki veri tipi: {dataTypeSeries}")

#ortalama harcama
meanSpend = monthlySpending.mean()
print(f"Ortalama harcama: {meanSpend:.3f} TL.")

Seri içindeki değerler: [2000 4050 3300 5060 9195 8200]
Seri içindeki indeksler: Index(['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran'], dtype='object')
Seri içindeki veri tipi: int64
Ortalama harcama: 5300.833 TL.

In [36]:
#4 DataFrame oluştur
#Sütunlar -> CustomerName, City, MonthlySpending, MembershipType (Amaç: Tablolu veri mantığı)
customerDataFrame = pd.DataFrame({
    "CustomerName": ["Ali", "Merve", "Suzan", "Kıvanc", "Canan"],
    "City": ["Ankara", "Bursa", "Ankara", "İstanbul", "Rize" ],
    "MonthlySpending": [5400, 2800, 6400, 7105, 8910],
    "MembershipType": ["Silver", "Platinum", "Gold", "Silver", "Bronze"]
    
})

customerDataFrame

  CustomerName      City  MonthlySpending MembershipType
0          Ali    Ankara             5400         Silver
1        Merve     Bursa             2800       Platinum
2        Suzan    Ankara             6400           Gold
3       Kıvanc  İstanbul             7105         Silver
4        Canan      Rize             8910         Bronze

In [37]:
#5 DataFrame Indeksleme

#Bir sütunu indeks olarak ayarla
columnIndexed = customerDataFrame.set_index("CustomerName")
columnIndexed

#indeks üzerinden satır seçme
columnIndexed.loc["Kıvanc"]

City               İstanbul
MonthlySpending        7105
MembershipType       Silver
Name: Kıvanc, dtype: object

In [38]:
#6 Index Değiştirme

#Indexi sıfırla (reset_index)
resetIndex = columnIndexed.reset_index()
resetIndex

#Yeni bir indeks tanımla (set_index)
newIndex = resetIndex.set_index("MembershipType")
newIndex

               CustomerName      City  MonthlySpending
MembershipType
Silver                  Ali    Ankara             5400
Platinum              Merve     Bursa             2800
Gold                  Suzan    Ankara             6400
Silver               Kıvanc  İstanbul             7105
Bronze                Canan      Rize             8910

In [39]:
#7 Multi-Index oluşturma
multiIndex = customerDataFrame.set_index(["City", "MembershipType"])
multiIndex

#Belli bir şehir-üyelik tipi seç
multiIndex.loc[("Ankara","Silver")]

CustomerName        Ali
MonthlySpending    5400
Name: (Ankara, Silver), dtype: object

In [42]:
#Son çıktı
#Toplam müşteri sayısı:
totalCustomers = len(customerDataFrame) #kaç satır yani kaç müşteri olduğunu veriyor

#En yüksek aylık harcama
maxMonthlySpending = customerDataFrame["MonthlySpending"].max() #max değeri bulacak

#En çok müşteri olan şehir
topCity = customerDataFrame["City"].value_counts().idxmax() #value_counts() bir sütundaki her bir unique değerin kaç kez tekrarladığını hesaplar ve büyükten küçüğe döndürür
#max() yazınca 2 döndürüyor ama idxmax() yazınca Ankara döndürüyor.
#idxmax(): index of maximumdur ve en büyük değer kimde sorusunun cevabıdır

print(f"Toplam müşteri sayısı: {totalCustomers}")
print(f"En yüksek aylık harcama: {maxMonthlySpending} TL.")
print(f"En çok müşteri olan şehir: {topCity}")

Toplam müşteri sayısı: 5
En yüksek aylık harcama: 8910 TL.
En çok müşteri olan şehir: Ankara