# Smart Sales & Customer Analytics System (Pandas – Advanced Review)

## Projenin Amacı:
Bir şirketin farklı kaynaklarda tutulan müşteri ve satış verilerini birleştirerek anlamlı analizler üretmeyi amaçlar. Gerçek hayatta veriler genellikle dağınık, eksik ve tutarsızdır. Bu projede verileri temizleyip, birleştirecek ve analiz edeceğiz.

## Pandas Neden Tercih Edilir?
Pandas veri analizi için güçlü ve esnek araçlar sunar.
- Farklı veri kaynaklarını birleştirme
- Eksik verileri temizleme
- Gruplandırma ve özetleme
- Excel ile çalışma
İş dünyasında en yaygın kullanılan veri analizi kütüphanelerindendir.

## Kapsanan Pandas Konuları:
- Eksik veriler (`isna`, `fillna`, `dropna`)
- Gruplandırma (`groupby`, `agg`)
- Veri birleştirme (`Concat`, `Merge`)
- Pandas ileri operasyonlar
- Excel ile çalışma (`read_excel`, `to_excel`)

### 2-Veri Setlerini Oluşturma

In [9]:
#Üç ayrı DataFrame oluştur
import pandas as pd
import numpy as np

#1-Customers DF
customers = pd.DataFrame({
    "CustomerID": [99, 100,102,103,104,105,206,207,208,210],
    "CustomerName":["Doja","Katy","Cardi", "Wayne", "Jennie","Fouzia","Jony","Ariana" ,"Abel","Rihanna"],
    "City": ["Los Angeles","London","İstanbul","İstanbul","Seoul","Paris","Moscow","New York", "Los Angeles","London"],
    "Age" : [30, 41, 33, np.nan, 30, 25, 28, 32, np.nan, 38] #bazı yaşlar eksik
})

#2-Sales DF
sales = pd.DataFrame({
    "SaleID": [1,2,3,4,5,6,7,8],
    "CustomerID": [99, 100,102,103,104,105,206,207],
    "Product": ["Laptop","Kulaklık","Telefon","Kulaklık", "Tablet", "Laptop","Telefon","Saç maşası"],
    "Amount": [45000, 2300, np.nan, np.nan, 12860, 72950, 37000, 3100] #bazı değerler nan
})

#3-Regions DF
regions = pd.DataFrame({
    "City": ["Los Angeles", "London", "İstanbul","Seoul","Paris","Moscow","New York"],
    "Region": ["West America", "Europe","Asia","Asia", "Europe", "Asia","East America"],
})

print("CUSTOMERS")
display(customers)
print("---------------------------------------------------------- ")
print(" ")

print("SALES")
display(sales)
print("---------------------------------------------------------- ")
print(" ")

print("REGIONS")
display(regions)

CUSTOMERS

   CustomerID CustomerName         City   Age
0          99         Doja  Los Angeles  30.0
1         100         Katy       London  41.0
2         102        Cardi     İstanbul  33.0
3         103        Wayne     İstanbul   NaN
4         104       Jennie        Seoul  30.0
5         105       Fouzia        Paris  25.0
6         206         Jony       Moscow  28.0
7         207       Ariana     New York  32.0
8         208         Abel  Los Angeles   NaN
9         210      Rihanna       London  38.0

----------------------------------------------------------

SALES

   SaleID  CustomerID     Product   Amount
0       1          99      Laptop  45000.0
1       2         100    Kulaklık   2300.0
2       3         102     Telefon      NaN
3       4         103    Kulaklık      NaN
4       5         104      Tablet  12860.0
5       6         105      Laptop  72950.0
6       7         206     Telefon  37000.0
7       8         207  Saç maşası   3100.0

----------------------------------------------------------

REGIONS

          City        Region
0  Los Angeles  West America
1       London        Europe
2     İstanbul          Asia
3        Seoul          Asia
4        Paris        Europe
5       Moscow          Asia
6     New York  East America

### 3-Eksik Veriler

In [16]:
#Eksik değerleri tespit edelim
#customers icin
customersEksikDeger = customers.isna().sum() 
print(f"Customers Eksik değerleri: {customersEksikDeger}")
print(" ")
#sales icin
salesEksikDeger = sales.isna().sum()
print(f"Sales Eksik değerleri: {salesEksikDeger}")
print(" ")
#Yaş için ortalama (mean) ile doldur
yasOrtalama = customers["Age"].mean() #yaş ortalamasını aldık
customers["Age"] = customers["Age"].fillna(yasOrtalama) #yasOrtalamadan gelen sonuç ile doldurduk ve yaşlara eşitledik
print("Yaş ortalaması ile customers değerleri dolduruldu.")
display(customers)

#Satış tutarı eksik olan kayıtları sil
salesClean = sales.dropna(subset=["Amount"])
print("Temizlenmiş satış verisi")
display(salesClean)

Customers Eksik değerleri: CustomerID      0
CustomerName    0
City            0
Age             0
dtype: int64

Sales Eksik değerleri: SaleID        0
CustomerID    0
Product       0
Amount        2
dtype: int64

Yaş ortalaması ile customers değerleri dolduruldu.

   CustomerID CustomerName         City     Age
0          99         Doja  Los Angeles  30.000
1         100         Katy       London  41.000
2         102        Cardi     İstanbul  33.000
3         103        Wayne     İstanbul  32.125
4         104       Jennie        Seoul  30.000
5         105       Fouzia        Paris  25.000
6         206         Jony       Moscow  28.000
7         207       Ariana     New York  32.000
8         208         Abel  Los Angeles  32.125
9         210      Rihanna       London  38.000

Temizlenmiş satış verisi

   SaleID  CustomerID     Product   Amount
0       1          99      Laptop  45000.0
1       2         100    Kulaklık   2300.0
4       5         104      Tablet  12860.0
5       6         105      Laptop  72950.0
6       7         206     Telefon  37000.0
7       8         207  Saç maşası   3100.0

### 4-Merge işlemi

In [20]:
# customers + sales -> customerID üzerinden birleştir
# ortaya çıkan tabloyu regions ile birleştir
#left-> customers, right->salesClean
customersSales = pd.merge(customers, salesClean, how="inner", on="CustomerID") #sadece satış yapan müşteriler kalsın dediğimiz için inner

#regions ekle -> City üzerinden ekleriz
tamBirlesmisHal = pd.merge(customersSales, regions, how="left", on="City") #tüm müşteriler kalsın, region varsa eklensin

display(tamBirlesmisHal)

,CustomerID,CustomerName,City,Age,SaleID,Product,Amount,Region
0,99,Doja,Los Angeles,30.0,1,Laptop,45000.0,West America
1,100,Katy,London,41.0,2,Kulaklık,2300.0,Europe
2,104,Jennie,Seoul,30.0,5,Tablet,12860.0,Asia
3,105,Fouzia,Paris,25.0,6,Laptop,72950.0,Europe
4,206,Jony,Moscow,28.0,7,Telefon,37000.0,Asia
5,207,Ariana,New York,32.0,8,Saç maşası,3100.0,East America

### 5-Groupby ile Gruplandırma

In [26]:
#Şehir bazlı toplam satış
#agg()-> aggretion yani özetlemedir. veriyi gruplayıp özet hesaplar yani toplam, ortalama, sayım, min/max vb.
citySale = tamBirlesmisHal.groupby("City").agg(ToplamSatis = ("Amount","sum")) #Şehire göre gruplar, her grup için amount sütununu toplar
print("Şehir bazlı toplam satış")
display(citySale)
print(" ")

#Bölge bazlı ortalama satış
regionSale = tamBirlesmisHal.groupby("Region").agg(OrtalamaSatis = ("Amount", "mean"))
print("Bölge bazlı ortalama satış")
display(regionSale)
print(" ")

#Ürün bazlı satış sayısı
productSale = tamBirlesmisHal.groupby("Product").agg(UrunSatis = ("Amount","count"))
print("Ürün bazlı satış sayısı:")
display(productSale)

Şehir bazlı toplam satış

             ToplamSatis
City
London            2300.0
Los Angeles      45000.0
Moscow           37000.0
New York          3100.0
Paris            72950.0
Seoul            12860.0

Bölge bazlı ortalama satış

              OrtalamaSatis
Region
Asia                24930.0
East America         3100.0
Europe              37625.0
West America        45000.0

Ürün bazlı satış sayısı:

            UrunSatis
Product
Kulaklık            1
Laptop              2
Saç maşası          1
Tablet              1
Telefon             1

### 6-Concat İşlemleri

In [28]:
#Farklı aylara ait iki satış tablosu oluştur. Satır bazlı birleştir(axis=0)
salesMart = pd.DataFrame({
    "SaleID": [1,5,7,8],
    "CustomerID": [99,104,206,207],
    "Product": ["Laptop","Tablet","Telefon","Saç maşası"],
    "Amount": [45000, 12860, 37000, 3100],
    "Month": ["2026-03", "2026-03", "2026-03", "2026-03"]
})

salesEyl = pd.DataFrame({
    "SaleID": [2,6,7],
    "CustomerID": [100,105,207],
    "Product": ["Kulaklık","Laptop","Saç maşası"],
    "Amount": [2300,72950, 3100],
    "Month": ["2026-09", "2026-09", "2026-09"]
    
})

#Satır bazlı birleştirelim
salesAllMonths = pd.concat([salesMart,salesEyl], axis=0, ignore_index=True)
print("Mart satışları")
display(salesMart)
print(" ")

print("Eylül satışları")
display(salesEyl)
print(" ")

print("Birleştirilmiş aylık satışlar")
display(salesAllMonths)

Mart satışları

   SaleID  CustomerID     Product  Amount    Month
0       1          99      Laptop   45000  2026-03
1       5         104      Tablet   12860  2026-03
2       7         206     Telefon   37000  2026-03
3       8         207  Saç maşası    3100  2026-03

Eylül satışları

   SaleID  CustomerID     Product  Amount    Month
0       2         100    Kulaklık    2300  2026-09
1       6         105      Laptop   72950  2026-09
2       7         207  Saç maşası    3100  2026-09

Birleştirilmiş aylık satışlar

   SaleID  CustomerID     Product  Amount    Month
0       1          99      Laptop   45000  2026-03
1       5         104      Tablet   12860  2026-03
2       7         206     Telefon   37000  2026-03
3       8         207  Saç maşası    3100  2026-03
4       2         100    Kulaklık    2300  2026-09
5       6         105      Laptop   72950  2026-09
6       7         207  Saç maşası    3100  2026-09

### 7-Pandas ile İleri Operasyonlar

In [31]:
#Koşullu filtreleme
yuksekSatis = salesAllMonths[salesAllMonths["Amount"] > 20000]
print("20 bin üstü fiyata sahip olan satışlar: ")
display(yuksekSatis)
print(" ")

#Yeni sütun oluşturma (Örn: KDV eklenmiş satır) %20 kdv ekleyelim
salesAllMonths["KDV"] = salesAllMonths["Amount"] * 1.20
print("KDV eklenmiş satış tutarı: ")
display(salesAllMonths)

#apply() kullanımı -> Satış tutarına göre kategori oluşturalım
def satisKategori(amount):
    if amount >= 40000:
        return "Premium"
    elif amount >= 25000:
        return "Gold"
    elif amount >= 10000:
        return "Standard"
    else:
        return "Basic"

salesAllMonths["Category"] = salesAllMonths["Amount"].apply(satisKategori)
print("Kateogri eklenmiş hali: ")
display(salesAllMonths)

20 bin üstü fiyata sahip olan satışlar:

   SaleID  CustomerID  Product  Amount    Month      KDV
0       1          99   Laptop   45000  2026-03  54000.0
2       7         206  Telefon   37000  2026-03  44400.0
5       6         105   Laptop   72950  2026-09  87540.0

KDV eklenmiş satış tutarı:

   SaleID  CustomerID     Product  Amount    Month      KDV
0       1          99      Laptop   45000  2026-03  54000.0
1       5         104      Tablet   12860  2026-03  15432.0
2       7         206     Telefon   37000  2026-03  44400.0
3       8         207  Saç maşası    3100  2026-03   3720.0
4       2         100    Kulaklık    2300  2026-09   2760.0
5       6         105      Laptop   72950  2026-09  87540.0
6       7         207  Saç maşası    3100  2026-09   3720.0

Kateogri eklenmiş hali:

   SaleID  CustomerID     Product  Amount    Month      KDV  Category
0       1          99      Laptop   45000  2026-03  54000.0   Premium
1       5         104      Tablet   12860  2026-03  15432.0  Standard
2       7         206     Telefon   37000  2026-03  44400.0      Gold
3       8         207  Saç maşası    3100  2026-03   3720.0     Basic
4       2         100    Kulaklık    2300  2026-09   2760.0     Basic
5       6         105      Laptop   72950  2026-09  87540.0   Premium
6       7         207  Saç maşası    3100  2026-09   3720.0     Basic

### 8- Excel ile Çalışma

In [33]:
# Temizlenmiş ve analiz edilmiş tabloyu excel'e yaz
salesAllMonths.to_excel("final_sales_report.xlsx", index=False) #dosyayı oluşturdul
print("Excel dosyası yazıldı.")

#Excel dosyasını okuyalım
salesFromExcel = pd.read_excel("final_sales_report.xlsx") #dosyayı tekrar yükledik 
print("Excel'den okunan veri")
display(salesFromExcel)

Excel dosyası yazıldı.
Excel'den okunan veri

   SaleID  CustomerID     Product  Amount    Month    KDV  Category
0       1          99      Laptop   45000  2026-03  54000   Premium
1       5         104      Tablet   12860  2026-03  15432  Standard
2       7         206     Telefon   37000  2026-03  44400      Gold
3       8         207  Saç maşası    3100  2026-03   3720     Basic
4       2         100    Kulaklık    2300  2026-09   2760     Basic
5       6         105      Laptop   72950  2026-09  87540   Premium
6       7         207  Saç maşası    3100  2026-09   3720     Basic

In [35]:
#Toplam satış
totalSale = int(tamBirlesmisHal["Amount"].sum())
print(f"Toplam satış: {totalSale}")

#En karlı şehir (en yüksek toplam satış yapan şehir)
citySale = tamBirlesmisHal.groupby("City")["Amount"].sum()
eniyiSehir = citySale.idxmax()
print(f"En karlı şehir: {eniyiSehir}")

#En güçlü bölge (en yüksek toplam satış yapan bölge)
regionSale = tamBirlesmisHal.groupby("Region")["Amount"].sum()
enGucluBolge = regionSale.idxmax()
print(f"En güçlü bölge: {enGucluBolge}")

Toplam satış: 173210
En karlı şehir: Paris
En güçlü bölge: Europe